### PR TITLE
 [MIG] website_sale_suggest_create_account to v14.

### PR DESCRIPTION
**Pull request by sebasdrk17**
### What changed:

1. Added a new author to contributors
2. Added a new extra step to validate that the checkout buttons does not exist

### CODE REVIEW

**Comment by sebasdrk17** [comment]
Hello @dsolanki-initos, I had to create a PR since I don't have write access, could you review please and merge if possible?

I'll be around if I need to do any changes

Regards

**Comment by sebasdrk17** [comment]
Hello @dsolanki-initos any comments about this?

**Comment by oscarolar** [comment]
@initos-com @OSevangelist could you please merge?

**Comment by sebasdrk17** [comment]
Closing because a new PR will be created directly to OCA

Regards

**Pull request closed without merging**
